apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: cm6gb2nug-go
  janus-idp.io/tekton: cm6gb2nug-go
  backstage.io/kubernetes-id: cm6gb2nug-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: cm6gb2nug-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
